noticias/core/urls.py
from django.urls import path
from .views import index , buscadornoticias , registro , contacto ,contacto , detallenoticia , datoutil , galeriadefotos , login , mundo , nacional , nosotros , pagperiodista , registro , datoutil1 , datoutil2 , mundo1 , mundo2 , nacional1 , nacional2 , periodista1 , periodista2 , periodista3 , periodista4 , periodista5 , periodista6 , agregar_noticia , listar_noticia , modificar_noticia , eliminar_noticia

urlpatterns=[
    path('',index,name="index"),
    path('buscadornoticias/',buscadornoticias,name="buscadornoticias"),
    path('contacto/',contacto,name="contacto"),
    path('datoutil/',datoutil,name="datoutil"),
    path('detallenoticia/',detallenoticia,name="detallenoticia"),
    path('galeriadefotos/',galeriadefotos,name="galeriadefotos"),
    path('login/',login,name="login"),
    path('mundo/',mundo,name="mundo"),
    path('nacional/',nacional,name="nacional"),
    path('nosotros/',nosotros,name="nosotros"),
    path('pagperiodista/',pagperiodista,name="pagperiodista"),
    path('registro/',registro,name="registro"),
    path('datoutil1/',datoutil1,name="datoutil1"),
    path('datoutil2/',datoutil2,name="datoutil2"),
    path('mundo1/',mundo1,name="mundo1"),
    path('mundo2/',mundo2,name="mundo2"),
    path('nacional1/',nacional1,name="nacional1"),
    path('nacional2/',nacional2,name="nacional2"),
    path('periodista1/',periodista1,name="periodista1"),
    path('periodista2/',periodista2,name="periodista2"),
    path('periodista3/',periodista3,name="periodista3"),
    path('periodista4/',periodista4,name="periodista4"),
    path('periodista5/',periodista5,name="periodista5"),
    path('periodista6/',periodista6,name="periodista6"),
    path('agregar-noticia/',agregar_noticia,name="agregar_noticia"),
    path('listar-noticia/',listar_noticia,name="listar_noticia"),
    path('modificar-noticia/<id>/',modificar_noticia,name="modificar_noticia"),
    path('eliminar-noticia/<id>/',eliminar_noticia,name="eliminar_noticia"),
    path('registro/',registro,name="registro"),
]

noticias/noticias/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

noticias/core/models.py
from django.db import models

#Create your models here.
class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True,verbose_name="Id de Categoria")
    Categoria = models.CharField(max_length=50,verbose_name="Nombre de la categoria")
    
    def __str__(self):
        return self.Categoria


class Periodista(models.Model):
    NombrePeriodista = models.CharField( max_length=50 ,verbose_name="nombre de periodista")
    Edad =models.IntegerField(verbose_name="edad")
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    Ocupacion = models.CharField( max_length=200 ,verbose_name="ocupacion")
    CantidadNoticias = models.IntegerField(verbose_name="cantidad de noticias")
    imagen = models.ImageField(upload_to="periodistas",null=True)
    def __str__(self):
        return self.NombrePeriodista

class Noticia(models.Model):
    NombreNoticia = models.CharField( max_length=500 ,verbose_name="nombre de la noticia")
    Fecha =models.DateField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    Ubicacion = models.CharField( max_length=200 ,verbose_name="ubicacion")
    autor =models.ForeignKey(Periodista, on_delete=models.CASCADE, max_length=50,verbose_name="periodista")
    contenido = models.TextField()
    imagen = models.ImageField(upload_to="noticias",null=True)
    def __str__(self):
        return self.NombreNoticia

opciones_consultas=[
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencias"],
    [3, "felicitaciones"]
]

class Contacto(models.Model):
    nombre=models.CharField( max_length=50)
    correo =models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

noticias/core/forms.py
from django import forms
from .models import Contacto , Noticia
from django.contrib.auth.forms import UserCreationForm
class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'

class CustomUserCreationForm(UserCreationForm):
    pass

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = '__all__'
        widgets={
            "Fecha":forms.SelectDateWidget()
            }

noticias/core/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .models import Categoria , Periodista , Noticia
from .forms import ContactoForm , NoticiaForm , CustomUserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate , login
# Create your views here.


def index(request):
    noticia = Noticia.objects.all()
    datos={
        'noticias': noticia
    }
    return render(request,'core/index.html', datos)

def buscadornoticias(request):
    return render(request,'core/buscadornoticias.html')


def contacto(request):
    data={
        'form':ContactoForm()
    }

    if request.method =='POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"]="contacto guardado"
        else:
            data["form"]=formulario
    return render(request,'core/contacto.html',data)

def detallenoticia(request):
    noticia = Noticia.objects.filter(categoria=3)
    datos={
        'noticias': noticia
    }
    return render(request,'core/detallenoticia.html',datos)

def datoutil(request):
    return render(request,'core/datoutil.html')

def galeriadefotos(request):
    return render(request,'core/galeriadefotos.html')

def mundo(request):
    noticia = Noticia.objects.filter(categoria=1)
    datos={
        'noticias': noticia
    }
    return render(request,'core/mundo.html',datos)

def nacional(request):
    noticia = Noticia.objects.filter(categoria=2)
    datos={
        'noticias': noticia
    }
    return render(request,'core/nacional.html',datos)

def nosotros(request):
    return render(request,'core/nosotros.html')

def pagperiodista(request):
    return render(request,'core/pagperiodista.html')

def registro(request):
    return render(request,'core/registro.html')

def datoutil1(request):
    return render(request,'core/datoutil1.html')

def datoutil2(request):
    return render(request,'core/datoutil2.html')

def mundo1(request):
    return render(request,'core/mundo1.html')

def mundo2(request):
    return render(request,'core/mundo2.html')

def nacional1(request):
    return render(request,'core/nacional1.html')

def nacional2(request):
    return render(request,'core/nacional2.html')

def periodista1(request):
    return render(request,'core/periodista1.html')

def periodista2(request):
    return render(request,'core/periodista2.html')

def periodista3(request):
    return render(request,'core/periodista3.html')

def periodista4(request):
    return render(request,'core/periodista4.html')

def periodista5(request):
    return render(request,'core/periodista5.html')

def periodista6(request):
    return render(request,'core/periodista6.html')

def agregar_noticia(request):
    data={
        'form':NoticiaForm()
    }
    if request.method =='POST':
        formulario = NoticiaForm(data=request.POST,files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,"Noticia registrada")
        else:
            data["form"]=formulario
    return render(request,'core/noticia/agregar.html',data)

def listar_noticia(request):
    noticias= Noticia.objects.all()
    data={
        'noticias':noticias
    }
    return render(request,'core/noticia/listar.html',data)

def modificar_noticia(request,id):
    noticia=get_object_or_404(Noticia,id=id)
    data={
        'form':NoticiaForm(instance=noticia)
    }
    if request.method=='POST':
        formulario=NoticiaForm(data=request.POST,instance=noticia, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request,"modificado correctamente")
            return redirect(to="listar_noticia")
        data["form"]=formulario
    return render(request,'core/noticia/modificar.html',data)

def eliminar_noticia(request,id):
    noticia=get_object_or_404(Noticia,id=id)
    noticia.delete()
    messages.success(request,"eliminado correctamente")
    return redirect(to="listar_noticia")

def registro(request):
    data={
        'form':CustomUserCreationForm()
    }
    if request.method =='POST':
        formulario=CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user =authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request,user)
            messages.success(request,"te has registrado correctamente")
            return redirect("index")
        data["form"]=formulario
    return render(request,'registration/registro.html',data)

noticias/noticias/views.py
from django.http import HttpResponse 
def saludo (request):
    return HttpResponse("hola como estas me llamo camilo")

noticias/core/templates/core/noticia/agregar.html
{% extends 'core\base.html'%}
{% load static %}
{%block js%}
{%endblock%}
{%block contenido%}
{% load crispy_forms_tags %}
<div class="row">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card body" id="envmens">
                    <h2>Nueva Noticia</h2>
                    <form action="" class="formulario_contacto" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <div class="pading"></div>
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <button type="submit" class="btn btn-primary" id="enviarcontacto">Agregar</button>
                        </div>
                        </form>
                        {{mensaje}}
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

noticias/core/templates/core/noticia/listar.html
{% extends 'core\base.html'%}
{% load static %}
{%block js%}
<script>
    function eliminarnoticia(id){
        Swal.fire({
            "title":"¿estas seguro?",
            "text":"esta accion no se puede devolver",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText" :"No, Cancelar",
            "confirmButtonText":"Si,Eliminar"
        })
        .then(function(result){
            if(result.isConfirm){
                widow.location.href = "/eliminar-noticia/"+id+"/"
            }
        })
    }
</script>
{%endblock%}
{%block contenido%}
{% load crispy_forms_tags %}
<div class="card">
    <div class="card-body">
        <h2>Listado noticias</h2>
        <hr>
        <table class="table-striped table-hover table-responsive-sm">
            <tr>
                <th>Titulo</th>
                <th>Fecha</th>
                <th>Categoría</th>
                <th>Ubicación</th>
                <th>Opciones</th>
            </tr>

            {%for n in noticias%}
            <tr>
                <td>{{n.NombreNoticia}}</td>
                <td>{{n.Fecha}}</td>
                <td>{{n.categoria}}</td>
                <td>{{n.Ubicacion}}</td>
                <td>
                    {% if perms.core.change_noticia %}
                    <a href="{% url 'modificar_noticia' n.id %}" class="btn btn-info btn-sm">Editar</a>
                    {%endif%}
                    {% if perms.core.delete_noticia %}
                    <a href="#" onclick="eliminarnoticia({{n.id}})" class="btn btn-danger btn-sm">Eliminar</a>
                    {%endif%}
                </td>
            </tr>
            {%endfor%}

        </table>
    </div>
</div>
{%endblock%}

noticias/core/templates/core/noticia/modificar.html
{% extends 'core\base.html'%}
{% load static %}
{%block js%}
{%endblock%}
{%block contenido%}
{% load crispy_forms_tags %}
<div class="row">
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card body" id="envmens">
                    <h2>Editar Noticia</h2>
                    <form action="" class="formulario_contacto" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <div class="pading"></div>
                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="editar" class="btn btn-secondary">
                        </div>
                        </form>
                        {{mensaje}}
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}